package com.elianfabian.lapisbt.util

internal object AndroidInternalConstants {
	const val PAIRING_VARIANT_CONSENT = 3
	const val PAIRING_VARIANT_DISPLAY_PASSKEY = 4
	const val PAIRING_VARIANT_DISPLAY_PIN = 5
	const val PAIRING_VARIANT_OOB_CONSENT = 6
	const val PAIRING_VARIANT_PIN_16_DIGITS = 7

	const val UNBOND_REASON_AUTH_FAILED = 1
	const val UNBOND_REASON_AUTH_REJECTED = 2
	const val UNBOND_REASON_AUTH_CANCELED = 3
	const val UNBOND_REASON_REMOTE_DEVICE_DOWN = 4
	const val UNBOND_REASON_DISCOVERY_IN_PROGRESS = 5
	const val UNBOND_REASON_AUTH_TIMEOUT = 6
	const val UNBOND_REASON_REPEATED_ATTEMPTS = 7
	const val UNBOND_REASON_REMOTE_AUTH_CANCELED = 8
	const val UNBOND_REASON_REMOVED = 9
}
