-keepattributes RuntimeVisibleAnnotations,AnnotationDefault,Signature,InnerClasses,EnclosingMethod
-keep class com.elianfabian.lapisbt_rpc.annotation.** { *; }
-keep interface kotlinx.coroutines.flow.Flow { *; }
-keep interface kotlin.coroutines.Continuation { *; }
-keep class kotlin.Metadata { *; }
